import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "agl-orange": "var(--color-agl-orange)",
        "grays-white": "var(--color-grays-white)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-meta": "var(--color-text-meta)",
        "surface-metric": "var(--color-surface-metric)",
        "surface-page": "var(--color-surface-page)",
        "surface-card": "var(--color-surface-card)",
        "brand-orange": "var(--color-brand-orange)",
        "brand-green": "var(--color-brand-green)",
        "brand-rust": "var(--color-brand-rust)",
        "brand-gold": "var(--color-brand-gold)",
        "brand-brown": "var(--color-brand-brown)",
        "brand-gray": "var(--color-brand-gray)",
        "border-default": "var(--color-border-default)",
        "border-strong": "var(--color-border-strong)",
        "chart-track": "var(--color-chart-track)",
        "chart-budget": "var(--color-chart-budget)",
        "chart-local-trade": "var(--color-chart-local-trade)",
        "chart-projects": "var(--color-chart-projects)",
        "chart-export": "var(--color-chart-export)",
        "loss-value": "var(--color-loss-value)",
        "variance-favourable": "var(--color-variance-favourable)",
        "variance-unfavourable": "var(--color-variance-unfavourable)",
        "highlight-fill": "var(--color-highlight-fill)",
        "highlight-active": "var(--color-highlight-active)",
        "highlight-resolved": "var(--color-highlight-resolved)",
        "comment-marker": "var(--color-comment-marker)",
        "comment-border": "var(--color-comment-border)",
        "comment-surface": "var(--color-comment-surface)",
        "gate-bg": "var(--color-gate-bg)",
        "gate-surface": "var(--color-gate-surface)",
        "toc-active-text": "var(--color-toc-active-text)",
        "progress-bar": "var(--color-progress-bar)",
        "selection-toolbar-bg": "var(--color-selection-toolbar-bg)",
        "selection-toolbar-text": "var(--color-selection-toolbar-text)",
        "watermark": "var(--color-watermark)",
        link: "var(--color-link)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)", "system-ui", "sans-serif"],
        numerals: ["var(--font-family-numerals)", "var(--font-family-sans)", "sans-serif"],
      },
      fontSize: {
        "display-cover": ["var(--text-display-cover-size)", { lineHeight: "var(--text-display-cover-leading)" }],
        "heading-cover-sub": ["var(--text-heading-cover-sub-size)", { lineHeight: "var(--text-heading-cover-sub-leading)", letterSpacing: "var(--text-heading-cover-sub-tracking)" }],
        "heading-section": ["var(--text-heading-section-size)", { lineHeight: "var(--text-heading-section-leading)", letterSpacing: "var(--text-heading-section-tracking)" }],
        "heading-subsection": ["var(--text-heading-subsection-size)", { lineHeight: "var(--text-heading-subsection-leading)", letterSpacing: "var(--text-heading-subsection-tracking)" }],
        "heading-toc": ["var(--text-heading-toc-size)", { lineHeight: "var(--text-heading-toc-leading)", letterSpacing: "var(--text-heading-toc-tracking)" }],
        body: ["var(--text-body-size)", { lineHeight: "var(--text-body-leading)" }],
        meta: ["var(--text-meta-size)", { lineHeight: "var(--text-meta-leading)" }],
        "label-metric": ["var(--text-label-metric-size)", { lineHeight: "var(--text-label-metric-leading)", letterSpacing: "var(--text-label-metric-tracking)" }],
        "value-metric": ["var(--text-value-metric-size)", { lineHeight: "var(--text-value-metric-leading)" }],
        "label-table": ["var(--text-label-table-size)", { lineHeight: "var(--text-label-table-leading)", letterSpacing: "var(--text-label-table-tracking)" }],
        "cell-table": ["var(--text-cell-table-size)", { lineHeight: "var(--text-cell-table-leading)" }],
        "label-chart": ["var(--text-label-chart-size)", { lineHeight: "var(--text-label-chart-leading)", letterSpacing: "var(--text-label-chart-tracking)" }],
        "value-chart": ["var(--text-value-chart-size)", { lineHeight: "var(--text-value-chart-leading)" }],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        rail: "var(--shadow-rail)",
      },
      spacing: {
        "page-x": "var(--space-page-x)",
        "card-inner": "var(--space-card-inner)",
        "section-top": "var(--space-section-top)",
        "metric-gap": "var(--space-metric-gap)",
      },
      maxWidth: {
        prose: "var(--measure-prose)",
        content: "var(--measure-content)",
      },
      width: {
        "toc-rail": "var(--width-toc-rail)",
      },
      backgroundColor: {
        "table-row-hover": "var(--color-table-row-hover)",
        "toc-hover": "var(--color-toc-hover)",
      },
      borderColor: {
        "toc-active-border": "var(--color-toc-active-border)",
        "glossary-underline": "var(--color-glossary-underline)",
      },
      height: {
        "progress-bar": "var(--height-progress-bar)",
        "chart-bar": "var(--size-bar-height)",
        hero: "var(--height-hero)",
      },
    },
  },
  plugins: [],
};

export default config;
